FROM php:8.2-fpm

RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN curl -O https://wordpress.org/latest.tar.gz \
    && tar -xzf latest.tar.gz \
    && cp -r wordpress/* /var/www/html/ \
    && rm -rf wordpress latest.tar.gz \
    && chown -R www-data:www-data /var/www/html
